import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {once} from 'node:events';
import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createLocalJobs} from '../scripts/local-jobs.mjs';
const engineModule=await import('../local-engine/engine-operations.js').catch(error=>{if(error.code==='ERR_MODULE_NOT_FOUND')return import('../../process-studio/engine-operations.js');throw error});

test('engine cancellation waits for transcription to stop and immediately permits retry',async()=>{
 const module=engineModule;assert.equal(typeof module.createEngineOperations,'function','engine must expose cancellable processing');
 let entered,started=new Promise(resolve=>entered=resolve),stopped=false;const runtime={speechReady:true,status:async()=>({ai:true}),transcribe:async(bytes,{signal})=>{entered();await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>{stopped=true;reject(signal.reason)},{once:true}));}};
 const readBody=async req=>{const parts=[];for await(const part of req)parts.push(part);return Buffer.concat(parts)};
 const send=(res,status,data)=>{if(!res.destroyed&&!res.writableEnded){res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(data))}};
 const handler=module.createEngineOperations({runtime,readBody,send,windowsSpeechReady:Promise.resolve(false),analyze:async()=>({})});const server=http.createServer(async(req,res)=>{if(!await handler(req,res))send(res,404,{})});server.listen(0,'127.0.0.1');await once(server,'listening');const origin='http://127.0.0.1:'+server.address().port;
 try{const first=fetch(origin+'/api/transcribe-local',{method:'POST',headers:{'content-type':'audio/wav','x-operation-id':'first-operation'},body:'synthetic audio'});await started;const cancel=await fetch(origin+'/api/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operationId:'first-operation'})});assert.equal(cancel.status,200);assert.equal((await cancel.json()).stopped,true);assert.equal(stopped,true);assert.equal((await first).status,499);
  runtime.transcribe=async()=>({transcript:'Retry completed.'});const retry=await fetch(origin+'/api/transcribe-local',{method:'POST',headers:{'content-type':'audio/wav','x-operation-id':'retry-operation'},body:'synthetic audio'});assert.equal(retry.status,200);assert.equal((await retry.json()).transcript,'Retry completed.');const early=await fetch(origin+'/api/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operationId:'late-operation'})});assert.equal((await early.json()).stopped,true);const late=await fetch(origin+'/api/transcribe-local',{method:'POST',headers:{'content-type':'audio/wav','x-operation-id':'late-operation'},body:'synthetic audio'});assert.equal(late.status,499);
 }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve))}
});

test('job cancellation acknowledges stopped engine work before reporting cancelled',async()=>{
 const {createEngineOperations}=engineModule;let entered,started=new Promise(resolve=>entered=resolve),stopped=false;
 const runtime={speechReady:true,transcribe:async(bytes,{signal})=>{entered();await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>setTimeout(()=>{stopped=true;reject(signal.reason)},100),{once:true}))}};
 const readBody=async req=>{const parts=[];for await(const part of req)parts.push(part);return Buffer.concat(parts)},send=(res,status,data)=>{if(!res.destroyed&&!res.writableEnded){res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(data))}};
 const handler=createEngineOperations({runtime,readBody,send,windowsSpeechReady:Promise.resolve(false)}),server=http.createServer(async(req,res)=>{if(!await handler(req,res))send(res,404,{})});server.listen(0,'127.0.0.1');await once(server,'listening');const engine='http://127.0.0.1:'+server.address().port,root=path.resolve(os.tmpdir()),directory=await fs.mkdtemp(path.join(root,'ps-cancel-'));
 try{const jobs=createLocalJobs(directory,(url,options)=>fetch(engine+new URL(url).pathname,options));const request=(suffix,options={})=>new Request('http://127.0.0.1:4182/api/local/jobs'+suffix,{...options,headers:{origin:'http://127.0.0.1:4182',cookie:'ps_owner=test',...options.headers}});const first=await(await jobs(request('',{method:'POST',headers:{'x-job-key':'cancel-first','x-job-stage':'transcribe','content-type':'audio/wav'},body:'audio'}))).json();await started;
  const response=await jobs(request('/'+first.id,{method:'DELETE'}));assert.equal(response.status,200);assert.equal((await response.json()).status,'cancelled');assert.equal(stopped,true);runtime.transcribe=async()=>({transcript:'Immediate same-input retry.'});const retried=await jobs(request('',{method:'POST',headers:{'x-job-key':'cancel-first','x-job-stage':'transcribe','content-type':'audio/wav'},body:'audio'}));const retriedJob=await retried.json();assert.equal(retried.status,202);let status;for(let i=0;i<100;i++){status=await(await jobs(request('/'+retriedJob.id))).json();if(status.status==='complete')break;await new Promise(resolve=>setTimeout(resolve,5))}assert.equal(status.status,'complete');
 }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));assert.equal(path.dirname(directory),root);await fs.rm(directory,{recursive:true,force:true})}
});
