import test from 'node:test';import assert from 'node:assert/strict';
import hosted from '../worker/hosted.js';import {MemoryR2} from './fixtures/memory-r2.mjs';
const studio='https://vercel-logged-out.vercel.app',edge='https://media.test.workers.dev';
test('an owned trashed video can be backed up without making a revoked share playable',async()=>{
 const env={RECORDINGS:new MemoryR2(),STUDIO_ORIGIN:studio,MEDIA_ORIGIN:edge,STUDIO_RELAY_SECRET:'r'.repeat(40),MEDIA_SIGNING_SECRET:'m'.repeat(40),PUBLIC_RATE_LIMITER:{limit:async()=>({success:true})}};
 const api=(path,options={})=>hosted.fetch(new Request(edge+path,{...options,headers:{origin:studio,cookie:'ps_owner='+'1'.repeat(32),'x-studio-relay':env.STUDIO_RELAY_SECRET,...options.headers}}),env);
 const grant=await(await api('/api/uploads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key:'trash-backup-check',size:4,mime:'video/webm',filename:'test.webm'})})).json();await hosted.fetch(new Request(grant.uploadUrl,{method:'PUT',headers:{origin:studio,'content-type':'video/webm'},body:new Uint8Array(4)}),env);const saved=await(await api('/api/uploads/'+grant.uploadId+'/complete',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).json();await api('/api/recordings/'+saved.id,{method:'DELETE'});
 const backup=await(await api('/api/recordings/'+saved.id+'?includeDeleted=true')).json();const download=await hosted.fetch(new Request(backup.videoUrl),env);assert.equal(download.status,200);assert.equal((await download.arrayBuffer()).byteLength,4);assert.equal((await api('/api/recordings/'+saved.id)).status,410);
});
class Video extends EventTarget {constructor(){super();this.currentTime=96;this.duration=300;this.paused=true;this._src='';}get src(){return this._src}set src(value){this._src=value;this.currentTime=0;queueMicrotask(()=>this.dispatchEvent(new Event('loadedmetadata')))}pause(){this.paused=true}play(){this.paused=false;return Promise.resolve()}load(){}removeAttribute(name){if(name==='src')this._src=''}}
test('expired playback renews the permission and preserves the replay position',async()=>{
 const module=await import('../public/playback.js').catch(error=>{if(error.code==='ERR_MODULE_NOT_FOUND')return {};throw error});assert.equal(typeof module.setupManagedPlayback,'function','player must recover expiring media permissions');const video=new Video(),old='https://media.test.workers.dev/transfer/video/old.token',next='https://media.test.workers.dev/transfer/video/new.token';video._src=old;
 const status={textContent:''},retry=new EventTarget();const player=module.setupManagedPlayback(video,{recordPath:'/api/shared/'+'a'.repeat(32),record:{videoUrl:old},status,retry,baseUrl:studio,fetchImpl:async()=>Response.json({videoUrl:next})});try{await player.refresh({force:true});assert.equal(video.src,next);assert.equal(video.currentTime,96);assert.equal(video.paused,true)}finally{player.dispose()}
});
test('a revoked result is never renewed into playable media',async()=>{
 const module=await import('../public/playback.js').catch(error=>{if(error.code==='ERR_MODULE_NOT_FOUND')return {};throw error});assert.equal(typeof module.setupManagedPlayback,'function');const video=new Video();video._src=edge+'/transfer/video/old.token';const status={textContent:''},retry=new EventTarget();const player=module.setupManagedPlayback(video,{recordPath:'/api/shared/'+'a'.repeat(32),record:{videoUrl:video.src},status,retry,baseUrl:studio,fetchImpl:async()=>Response.json({error:'Share link revoked.'},{status:404})});try{await player.refresh({force:true});assert.equal(video.src,'');assert.match(status.textContent,/revoked/i)}finally{player.dispose()}
});
