import crypto from 'node:crypto';
import {createChatGPTVault} from './chatgpt-vault.mjs';
import {locked,warningMessages} from '../worker/storage-controls.js';
const remote='https://vercel-logged-out.vercel.app';
const json=(value,status=200)=>Response.json(value,{status,headers:{'cache-control':'no-store'}});
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
export function createLocalSharing({directory,vault=createChatGPTVault(directory),fetchImpl=fetch,loadRecord}){
 async function call(path,state,{method='GET',data,headers={}}={}){const response=await fetchImpl(remote+path,{method,headers:{origin:remote,...headers,...(state?.ownerToken?{cookie:'ps_owner='+state.ownerToken}:{}),...(data?{'content-type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{}),redirect:'error',signal:AbortSignal.timeout(60000)});const result=await response.json();if(!response.ok)fail(result.error||'Hosted sharing failed. Your local recording was kept.',response.status);return {result,response};}
 return async request=>{const url=new URL(request.url),prefix='/api/local/sharing/';if(!url.pathname.startsWith(prefix))return null;try{if(!['127.0.0.1','localhost'].includes(url.hostname)||request.headers.get('origin')&&request.headers.get('origin')!==url.origin||request.headers.get('sec-fetch-site')==='cross-site')fail('Open sharing from your local studio.',403);const route=url.pathname.slice(prefix.length);if(route==='status'&&request.method==='GET'){const state=await vault.read();return json({available:true,connected:Boolean(state.ownerToken),destination:remote,links:Object.fromEntries(Object.entries(state.links||{}).map(([id,item])=>[id,{url:item.url||null,pendingRevocations:(item.previousIds||[]).length}]))});}if(request.method!=='POST')fail('Method not allowed.',405);if(request.headers.get('origin')!==url.origin)fail('Open sharing from your local studio.',403);const raw=await request.text();if(raw.length>4000)fail('Sharing request is too large.',413);let input;try{input=JSON.parse(raw)}catch{fail('Invalid sharing request.');}
 return await locked('local-sharing-'+directory,async()=>{const state=await vault.read();state.links||={};state.pending||={};if(route==='connect'){const {result:status}=await call('/api/status');if(!status.storage||!status.directUploads)fail('Hosted storage is not active yet. Your local app remains usable.',503);if(!state.ownerToken){const {response}=await call('/api/session');const token=/ps_owner=([a-f0-9]{32})/.exec(response.headers.get('set-cookie')||'')?.[1];if(!token)fail('The hosted workspace could not be created.',502);state.ownerToken=token;await vault.write(state);}return json({connected:true,destination:remote});}
 if(route==='disconnect'){if(Object.keys(state.links).length&&!input.acknowledgeLinks)fail('Disconnecting keeps existing online links active. Revoke them first, or confirm that you will keep your hosted workspace recovery key.');delete state.ownerToken;state.links={};state.pending={};state.attempts={};await vault.write(state);return json({connected:false});}
 if(route==='recover'){if(input.format!=='process-studio-workspace-recovery'||input.version!==1||!/^[a-f0-9]{32}$/.test(input.token||''))fail('Choose a private hosted workspace key.');await call('/api/workspace/recover',null,{method:'POST',data:input});state.ownerToken=input.token;state.links={};state.pending={};await vault.write(state);return json({connected:true,recovered:true});}
 if(!state.ownerToken)fail('Connect hosted sharing in Settings first.',409);
 if(route==='recovery')return json({format:'process-studio-workspace-recovery',version:1,token:state.ownerToken,private:true,warning:'Keep this private key offline. Anyone with it can access the hosted workspace.'});
 if(!/^[a-f0-9]{32}$/.test(input.id||''))fail('Choose a saved recording.');
 if(route==='revoke'){const item=state.links[input.id];if(item){for(const id of [...new Set([item.remoteId,...(item.previousIds||[])])])await call('/api/recordings/'+id+'/share',state,{method:'DELETE'});delete state.links[input.id];await vault.write(state);}return json({revoked:true});}
 if(route!=='publish')fail('Sharing route not found.',404);if(input.consent!==true)fail('Confirm that anyone with the online link may view this snapshot.');const record=await loadRecord(input.id,request),sourceRevision=record.revision;if(input.expectedRevision!=null&&input.expectedRevision!==record.revision)fail('The local source changed. Reload this result before publishing.',409);if(!record.result||record.method==='stale'||!record.result.steps.length)fail('Generate a current process before publishing.');if(record.mime&&!record.reviewed)fail('Review the transcript before publishing.');if(record.result.steps.some(step=>!step.decisionReviewed))fail('Review every process decision before publishing.');if(warningMessages(record.result).length&&!input.warningsAcknowledged)fail('Acknowledge the source warnings before publishing.');
 const {result:hostedStatus}=await call('/api/status',state);if(!hostedStatus.storage||!hostedStatus.directUploads)fail('Hosted storage is not active yet.',503);
 const snapshot={transcript:record.transcript,transcriptSource:record.transcriptSource,reviewed:record.reviewed,segments:record.segments||[],result:record.result,method:record.method};const hash=crypto.createHash('sha256').update(JSON.stringify({localRecordId:input.id,snapshot,video:input.includeVideo===true&&Boolean(record.mime),size:record.size||0})).digest('hex'),key='online-'+hash+'-'+(state.attempts?.[input.id]||0);let pending=state.pending[input.id];if(pending&&!pending.uploaded&&pending.expiresAt<Date.now()){delete state.pending[input.id];state.attempts||={};state.attempts[input.id]=(state.attempts[input.id]||0)+1;await vault.write(state);fail('Upload permission expired. Retry publishing to create a new permission.',409);}if(!pending||pending.hash!==hash){if(input.includeVideo===true&&record.mime){const {result:allocation}=await call('/api/uploads',state,{method:'POST',data:{key,size:record.size,mime:record.mime,filename:record.filename,kind:record.kind}});pending={hash,remoteId:allocation.id,uploadId:allocation.uploadId,uploadUrl:allocation.uploadUrl,expiresAt:allocation.expiresAt,uploaded:allocation.status==='complete'};}else{const {result:created}=await call('/api/recordings',state,{method:'POST',headers:{'x-recording-key':key},data:{filename:record.filename,kind:'notes'}});pending={hash,remoteId:created.id,uploaded:true};}state.pending[input.id]=pending;await vault.write(state);}
 if(!pending.uploaded){const upload=new URL(pending.uploadUrl);if(upload.origin!==hostedStatus.mediaOrigin||upload.protocol!=='https:'||!upload.hostname.endsWith('.workers.dev')||upload.username||upload.password||upload.pathname!=='/transfer/upload/'+pending.uploadId)fail('Hosted upload destination failed validation.',502);const media=await loadRecord(input.id,request,{media:true});if(media.revision!==sourceRevision)fail('The source changed before upload. Reload before publishing.',409);const response=await fetchImpl(upload.href,{method:'PUT',headers:{origin:remote,'content-type':record.mime},body:media.bytes,redirect:'error',signal:AbortSignal.timeout(180000)});if(!response.ok&&response.status!==409)fail((await response.json()).error||'Upload failed.',response.status);await call('/api/uploads/'+pending.uploadId+'/complete',state,{method:'POST',data:{}});pending.uploaded=true;await vault.write(state);}
 const token=/ps_owner=([a-f0-9]{32})/.exec(request.headers.get('cookie')||'')?.[1];return await locked('record:'+crypto.createHash('sha256').update(token||'').digest('hex')+':'+input.id,async()=>{const current=await loadRecord(input.id,request);if(current.revision!==sourceRevision)fail('The local source changed during upload. Nothing was published; reload this result.',409);const {result:remoteRecord}=await call('/api/recordings/'+pending.remoteId,state);const {result:saved}=await call('/api/recordings/'+pending.remoteId,state,{method:'PUT',data:{...snapshot,expectedRevision:remoteRecord.revision}});const beforePublish=await loadRecord(input.id,request);if(beforePublish.revision!==sourceRevision)fail('The local source changed while saving online. Nothing was published; reload this result.',409);const {result:publication}=await call('/api/recordings/'+pending.remoteId+'/share',state,{method:'POST',data:{expectedRevision:saved.revision,consent:true,includeVideo:input.includeVideo===true,warningsAcknowledged:input.warningsAcknowledged===true}});if(!publication.url?.startsWith(remote+'/s/')||!/^https:\/\/vercel-logged-out\.vercel\.app\/s\/[a-f0-9]{32}$/.test(publication.url))fail('Hosted share address failed validation.',502);const previous=state.links[input.id];const previousIds=[...new Set([...(previous?.previousIds||[]),...(previous&&previous.remoteId!==pending.remoteId?[previous.remoteId]:[])])];state.links[input.id]={remoteId:pending.remoteId,url:publication.url,shareId:publication.shareId,previousIds};await vault.write(state);for(const oldId of [...previousIds]){try{await call('/api/recordings/'+oldId+'/share',state,{method:'DELETE'});state.links[input.id].previousIds=state.links[input.id].previousIds.filter(id=>id!==oldId);}catch{}}await vault.write(state);return json({url:publication.url,warning:state.links[input.id].previousIds.length?'The new link is ready, but an older link could not be revoked. Retry revocation from this result.':null},201);});
 });}catch(error){return json({error:error.status?error.message:'Online sharing could not complete. Your local source is preserved.'},error.status||500);}};
}
