import {createLocalDeletion} from './local-deletion.mjs';
import {createFileBucket} from './local-storage.mjs';
import {connectionCheck} from './connection-check.mjs';
import {desktopCameraBridge} from './desktop-camera-bridge.mjs';
import {localBridge} from './local-bridge.mjs';
import {createChatGPTProvider} from './chatgpt-provider.mjs';
import {createLocalJobs} from './local-jobs.mjs';
import {createLocalSharing} from './local-sharing.mjs';
import crypto from 'node:crypto';
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import worker from '../worker/index.js';
const directory=path.resolve('.preview-storage');await fs.mkdir(directory,{recursive:true});
const jobs=createLocalJobs(path.join(directory,'local-jobs'),fetch,{loadRecord:async(id,request)=>{const response=await worker.fetch(new Request(new URL('/api/recordings/'+id,request.url),{headers:{cookie:request.headers.get('cookie')}}),env),data=await response.json();if(!response.ok)throw Object.assign(Error(data.error),{status:response.status});return data;}});
const chatgpt=createChatGPTProvider({directory:path.resolve('.chatgpt-auth')});
const ownerStorage=createFileBucket(directory);let localOwner=null;const ownerObject=await ownerStorage.get('workspace-owner.json');if(ownerObject){try{localOwner=(await ownerObject.json()).token}catch(error){if(!error.storageCorrupt)throw error;await ownerStorage.recover('workspace-owner.json');localOwner=(await(await ownerStorage.get('workspace-owner.json')).json()).token}if(!/^[a-f0-9]{32}$/.test(localOwner||''))throw Error('Workspace ownership is damaged. Preserve workspace-owner.json and restore its backup before starting.');}
async function publicSource(request,response){const pathname=new URL(request.url).pathname;if(pathname.startsWith('/api/'))return response;const filename=pathname==='/'?'index.html':/^\/(r|s)\/[a-f0-9]{32}$/.test(pathname)?'result.html':/^\/[a-zA-Z0-9.-]+$/.test(pathname)?pathname.slice(1):null;if(!filename)return response;const source=await fs.readFile(['shared.js','decision-policy.js','local-analysis.js'].includes(filename)?filename:path.join('public',filename)).catch(()=>null);if(!source)return response;const headers=new Headers(response.headers);headers.delete('content-length');headers.set('content-type',({'.js':'text/javascript; charset=utf-8','.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.wav':'audio/wav','.svg':'image/svg+xml'})[path.extname(filename)]||'application/octet-stream');return new Response(source,{status:200,headers})}
const env={RECORDINGS:createFileBucket(directory),OPENAI_API_KEY:process.env.OPENAI_API_KEY,CREATOR_CODE:process.env.CREATOR_CODE};
const sharing=createLocalSharing({directory:path.resolve('.sharing-auth'),loadRecord:async(id,request,{media=false}={})=>{const response=await worker.fetch(new Request(new URL('/api/recordings/'+id,request.url),{headers:{cookie:request.headers.get('cookie')}}),env);const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error),{status:response.status});if(media){const playback=await worker.fetch(new Request(new URL('/api/recordings/'+id+'/video',request.url),{headers:{cookie:request.headers.get('cookie')}}),env);if(!playback.ok)throw Error('The local recording could not be read.');data.bytes=new Uint8Array(await playback.arrayBuffer());}return data;}});
const deletion=createLocalDeletion({env,jobs,sharing});
http.createServer(async(req,res)=>{try{const request=new Request('http://'+req.headers.host+req.url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:req,duplex:'half'}:{})});if(!['127.0.0.1:4182','localhost:4182'].includes(req.headers.host)){res.writeHead(403);return res.end('Local access only')}if(!localOwner){localOwner=/ps_owner=([a-f0-9]{32})/.exec(request.headers.get('cookie')||'')?.[1]||crypto.randomBytes(16).toString('hex');await ownerStorage.put('workspace-owner.json',JSON.stringify({token:localOwner}));}request.headers.set('cookie','ps_owner='+localOwner);let response=await sharing(request)||await chatgpt(request)||await connectionCheck(request)||await desktopCameraBridge(request)||await jobs(request)||await deletion(request)||await localBridge(request)||await worker.fetch(request,env);response=await publicSource(request,response);response.headers.set('set-cookie',`ps_owner=${localOwner}; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000`);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch{res.writeHead(500);res.end('Preview request failed')}}).listen(4182,'127.0.0.1',()=>console.log('Hosted-app preview at http://127.0.0.1:4182'));
