import {connectionCheck} from './connection-check.mjs';
import {desktopCameraBridge} from './desktop-camera-bridge.mjs';
import {localBridge} from './local-bridge.mjs';
import {createChatGPTProvider} from './chatgpt-provider.mjs';
import {createLocalJobs} from './local-jobs.mjs';
import {createLocalSharing} from './local-sharing.mjs';
import crypto from 'node:crypto';
import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import worker from '../worker/index.js';
const directory=path.resolve('.preview-storage');await fs.mkdir(directory,{recursive:true});
const jobs=createLocalJobs(path.join(directory,'local-jobs'));
const chatgpt=createChatGPTProvider({directory:path.resolve('.chatgpt-auth')});
const ownerFile=path.join(directory,'workspace-owner.json');let localOwner=await fs.readFile(ownerFile,'utf8').then(text=>JSON.parse(text).token).catch(()=>null);
class Bucket{async put(key,value,options={}){const file=path.join(directory,key);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,typeof value==='string'?value:new Uint8Array(value));if(options.httpMetadata)await fs.writeFile(file+'.meta',JSON.stringify(options.httpMetadata))}async get(key,options={}){const bytes=await fs.readFile(path.join(directory,key)).catch(()=>null);if(!bytes)return null;const start=options.range?.offset??0,length=options.range?.length??bytes.length;return {size:bytes.length,body:options.range?bytes.subarray(start,start+length):bytes,json:async()=>JSON.parse(bytes.toString()),arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}}async delete(key){await fs.unlink(path.join(directory,key)).catch(()=>{})}async list({prefix='',limit=50}){const rows=[];async function visit(folder){for(const item of await fs.readdir(folder,{withFileTypes:true}).catch(()=>[])){const file=path.join(folder,item.name);if(item.isDirectory())await visit(file);else{const key=path.relative(directory,file).replaceAll('\\','/');if(key.startsWith(prefix)&&!key.endsWith('.meta'))rows.push({key})}}}await visit(directory);return {objects:rows.slice(0,limit)}}}
async function publicSource(request,response){const pathname=new URL(request.url).pathname;if(pathname.startsWith('/api/'))return response;const filename=pathname==='/'?'index.html':/^\/(r|s)\/[a-f0-9]{32}$/.test(pathname)?'result.html':/^\/[a-zA-Z0-9.-]+$/.test(pathname)?pathname.slice(1):null;if(!filename)return response;const source=await fs.readFile(['shared.js','decision-policy.js','local-analysis.js'].includes(filename)?filename:path.join('public',filename)).catch(()=>null);if(!source)return response;const headers=new Headers(response.headers);headers.delete('content-length');headers.set('content-type',({'.js':'text/javascript; charset=utf-8','.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.wav':'audio/wav','.svg':'image/svg+xml'})[path.extname(filename)]||'application/octet-stream');return new Response(source,{status:200,headers})}
const env={RECORDINGS:new Bucket(),OPENAI_API_KEY:process.env.OPENAI_API_KEY,CREATOR_CODE:process.env.CREATOR_CODE};
const sharing=createLocalSharing({directory:path.resolve('.sharing-auth'),loadRecord:async(id,request,{media=false}={})=>{const response=await worker.fetch(new Request(new URL('/api/recordings/'+id,request.url),{headers:{cookie:request.headers.get('cookie')}}),env);const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error),{status:response.status});if(media){const playback=await worker.fetch(new Request(new URL('/api/recordings/'+id+'/video',request.url),{headers:{cookie:request.headers.get('cookie')}}),env);if(!playback.ok)throw Error('The local recording could not be read.');data.bytes=new Uint8Array(await playback.arrayBuffer());}return data;}});
http.createServer(async(req,res)=>{try{const request=new Request('http://'+req.headers.host+req.url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:req,duplex:'half'}:{})});if(!['127.0.0.1:4182','localhost:4182'].includes(req.headers.host)){res.writeHead(403);return res.end('Local access only')}if(!localOwner){localOwner=/ps_owner=([a-f0-9]{32})/.exec(request.headers.get('cookie')||'')?.[1]||crypto.randomBytes(16).toString('hex');await fs.writeFile(ownerFile,JSON.stringify({token:localOwner}));}request.headers.set('cookie','ps_owner='+localOwner);let response=await sharing(request)||await chatgpt(request)||await connectionCheck(request)||await desktopCameraBridge(request)||await jobs(request)||await localBridge(request)||await worker.fetch(request,env);response=await publicSource(request,response);response.headers.set('set-cookie',`ps_owner=${localOwner}; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000`);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch{res.writeHead(500);res.end('Preview request failed')}}).listen(4182,'127.0.0.1',()=>console.log('Hosted-app preview at http://127.0.0.1:4182'));
