import {locked,limit,reserveQuota,mediaResponse} from './storage-controls.js';
export const json=(value,status=200,headers={})=>Response.json(value,{status,headers:{'cache-control':'no-store','referrer-policy':'no-referrer',...headers}});
export const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};
export const digest=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');
export function ownerToken(request){const token=/ps_owner=([a-f0-9]{32})(?:;|$)/.exec(request.headers.get('cookie')||'')?.[1];if(!token)fail('Open your workspace first.',401);return token;}
export async function boundedBody(request,max){const reader=request.body?.getReader();if(!reader)return new Uint8Array();let length=0;const parts=[];while(true){const {done,value}=await reader.read();if(done)break;length+=value.length;if(length>max){await reader.cancel();fail('Upload exceeds its permitted size.',413)}parts.push(value);}const bytes=new Uint8Array(length);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}return bytes;}
export async function readJson(request,max=4*1024*1024){try{return JSON.parse(new TextDecoder().decode(await boundedBody(request,max)))}catch(error){if(error.status)throw error;fail('Invalid request data.');}}
export async function capacity(env,bytes,records=0){const bucket=env.RECORDINGS,key='controls/storage.json';return locked('capacity',async()=>{for(let attempt=0;attempt<8;attempt++){const object=await bucket.get(key),value=object?await object.json():{bytes:0,records:0};value.bytes=Math.max(0,(value.bytes||0)+bytes);value.records=Math.max(0,(value.records||0)+records);if(value.bytes>limit(env,'MAX_STORAGE_BYTES',500*1024*1024)||value.records>limit(env,'MAX_TOTAL_RECORDINGS',100))fail('Hosted storage is full. Remove unused hosted recordings or contact the operator.',429);const saved=await bucket.put(key,JSON.stringify(value),{onlyIf:object?{etagMatches:object.etag}:{etagDoesNotMatch:'*'}});if(saved!==null)return value;}fail('Storage admission is busy. Retry shortly.',503);});}
const mimeAllowed=new Set(['video/webm','video/mp4','audio/webm','audio/mp4','audio/mpeg','audio/wav','audio/x-wav','audio/ogg']);
const grantKey=id=>'uploads/grants/'+id+'.json';
const dataKey=grant=>`owners/${grant.owner}/${grant.recordId}.json`;
const mediaKey=grant=>`media/${grant.owner}/${grant.recordId}`;
const tempKey=grant=>'uploads/media/'+grant.id;
async function grantFor(env,id,request,owned=true){if(!/^[a-f0-9]{32}$/.test(id))fail('Upload not found.',404);const object=await env.RECORDINGS.get(grantKey(id));if(!object)fail('Upload not found.',404);const grant=await object.json();if(owned&&grant.owner!==await digest(ownerToken(request)))fail('Upload not found.',404);return {object,grant};}
async function putGrant(env,grant,object){const saved=await env.RECORDINGS.put(grantKey(grant.id),JSON.stringify(grant),{onlyIf:{etagMatches:object.etag}});if(saved===null)fail('Upload is already being handled. Retry its status shortly.',409);return saved;}
const uploadData=(env,grant)=>({uploadId:grant.id,id:grant.recordId,expiresAt:grant.expiresAt,status:grant.status,uploadUrl:env.MEDIA_ORIGIN+'/transfer/upload/'+grant.id});
export async function allocateUpload(request,env,core){if(env.UPLOADS_PAUSED==='true')fail('New hosted uploads are paused. Your local source is preserved.',503);const input=await readJson(request,2000),owner=await digest(ownerToken(request));if(!Number.isSafeInteger(input.size)||input.size<1||input.size>25*1024*1024)fail('Use media up to 25 MB.',413);if(!mimeAllowed.has(input.mime))fail('Use WebM, MP4, MP3, WAV or OGG.',415);if(!/^[a-zA-Z0-9_-]{8,128}$/.test(input.key||''))fail('Use a valid upload retry key.');const attempt=input.attempt??0;if(!Number.isInteger(attempt)||attempt<0||attempt>100)fail('Use a valid upload attempt.');const id=(await digest(owner+':'+input.key+(attempt?':attempt:'+attempt:''))).slice(0,32);return locked('upload:'+id,async()=>{const existing=await env.RECORDINGS.get(grantKey(id));if(existing){const grant=await existing.json();if(grant.size!==input.size||grant.mime!==input.mime||grant.filename!==String(input.filename||'walkthrough.webm').slice(0,120))fail('The retry key belongs to different media.',409);if(grant.status==='expired')fail('Upload expired. Begin a new upload.',410);return json(uploadData(env,grant));}
 await reserveQuota(env,'uploadBytes',input.size,limit(env,'MAX_DAILY_UPLOAD_BYTES',100*1024*1024),fail);await capacity(env,input.size,1);
 let recordPersisted=false,reservedRecords=1,bytesReserved=true;
 try{const create=await core(new Request(env.STUDIO_ORIGIN+'/api/recordings',{method:'POST',headers:{origin:env.STUDIO_ORIGIN,cookie:request.headers.get('cookie'),'content-type':'application/json','x-recording-key':input.key},body:JSON.stringify({filename:input.filename})}));const record=await create.json();if(!create.ok)fail(record.error,create.status);recordPersisted=true;if(create.status===200){await capacity(env,0,-1);reservedRecords=0;}if(record.mime){await capacity(env,-input.size);bytesReserved=false;const existingMedia=await env.RECORDINGS.get(`owners/${owner}/${record.id}.json`),existingRecord=await existingMedia.json();return json(uploadData(env,{id:existingRecord.uploadId,recordId:record.id,status:'complete',expiresAt:Date.now()+600000}));}const recordKey=`owners/${owner}/${record.id}.json`,recordObject=await env.RECORDINGS.get(recordKey),privateRecord=await recordObject.json();if(privateRecord.purging||privateRecord.deletedAt)fail('This upload placeholder is being removed. Retry shortly.',409);privateRecord.pendingUpload=id;privateRecord.revision++;const marked=await env.RECORDINGS.put(recordKey,JSON.stringify(privateRecord),{onlyIf:{etagMatches:recordObject.etag}});if(marked===null)fail('Upload allocation changed. Retry shortly.',409);const grant={id,owner,placeholderRevision:privateRecord.revision,recordId:record.id,size:input.size,mime:input.mime,kind:['screen','audio','import'].includes(input.kind)?input.kind:'import',filename:String(input.filename||'walkthrough.webm').slice(0,120),status:'allocated',expiresAt:Date.now()+600000,createdAt:Date.now()};const saved=await env.RECORDINGS.put(grantKey(id),JSON.stringify(grant),{onlyIf:{etagDoesNotMatch:'*'}});if(saved===null){await capacity(env,-input.size);bytesReserved=false;const other=await env.RECORDINGS.get(grantKey(id));return json(uploadData(env,await other.json()));}return json(uploadData(env,grant),201);}catch(error){if(bytesReserved)await capacity(env,-input.size,recordPersisted?0:-reservedRecords);throw error;}
 });}
export async function receiveUpload(request,env,id){return locked('upload:'+id,async()=>{let {object,grant}=await grantFor(env,id,request,false);if(grant.expiresAt<Date.now()||grant.status==='expired')fail('Upload permission expired. Begin a new upload.',410);if(grant.status!=='allocated')fail('This upload was already received or is in progress.',409);if((request.headers.get('content-type')||'').split(';')[0]!==grant.mime)fail('Upload MIME does not match its permission.',415);grant.status='receiving';const claim=await putGrant(env,grant,object);
 try{const bytes=await boundedBody(request,grant.size);if(bytes.length!==grant.size)fail('The upload is incomplete; retry this file.');await env.RECORDINGS.put(tempKey(grant),bytes,{httpMetadata:{contentType:grant.mime}});grant.status='received';await putGrant(env,grant,claim);return json({received:true,uploadId:id});}catch(error){await env.RECORDINGS.delete(tempKey(grant));grant.status='allocated';await putGrant(env,grant,claim).catch(()=>{});throw error;}
 });}
export async function finishUpload(request,env,id,core){return locked('upload:'+id,async()=>{const {object,grant}=await grantFor(env,id,request),recordObject=await env.RECORDINGS.get(dataKey(grant));if(!recordObject)fail('Recording not found.',404);const record=await recordObject.json();if(record.purging)fail('This recording is being removed.',410);if(record.uploadId===id&&record.mime){if(grant.status!=='complete'){grant.status='complete';await putGrant(env,grant,object);await env.RECORDINGS.delete(tempKey(grant));}return core(new Request(env.STUDIO_ORIGIN+'/api/recordings/'+record.id,{headers:{cookie:request.headers.get('cookie')}}));}if(grant.expiresAt<Date.now()||grant.status==='expired')fail('Upload permission expired.',410);if(grant.status!=='received')fail('Upload the complete file first.',409);if(record.mime)fail('This recording already has different media.',409);const media=await env.RECORDINGS.get(tempKey(grant));if(!media||media.size!==grant.size||media.httpMetadata?.contentType!==grant.mime)fail('Uploaded media failed verification.',422);
 await env.RECORDINGS.put(mediaKey(grant),media.body,{httpMetadata:{contentType:grant.mime}});Object.assign(record,{mime:grant.mime,size:grant.size,kind:grant.kind,filename:grant.filename,uploadId:id,revision:record.revision+1,updatedAt:new Date().toISOString()});const saved=await env.RECORDINGS.put(dataKey(grant),JSON.stringify(record),{onlyIf:{etagMatches:recordObject.etag}});if(saved===null)fail('This source changed during finalization. Retry the finalization.',409);grant.status='complete';await putGrant(env,grant,object);await env.RECORDINGS.delete(tempKey(grant));return core(new Request(env.STUDIO_ORIGIN+'/api/recordings/'+record.id,{headers:{cookie:request.headers.get('cookie')}}));
 });}
const encode=value=>btoa(String.fromCharCode(...value)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
const decode=value=>Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')),x=>x.charCodeAt(0));
const signingKey=env=>crypto.subtle.importKey('raw',new TextEncoder().encode(env.MEDIA_SIGNING_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);
export async function mediaUrl(env,descriptor){const payload=encode(new TextEncoder().encode(JSON.stringify({...descriptor,expiresAt:Date.now()+1200000}))),signature=encode(new Uint8Array(await crypto.subtle.sign('HMAC',await signingKey(env),new TextEncoder().encode(payload))));return env.MEDIA_ORIGIN+'/transfer/video/'+payload+'.'+signature;}
export async function readMedia(request,env,token){let descriptor;try{const parts=token.split('.');if(parts.length!==2||!await crypto.subtle.verify('HMAC',await signingKey(env),decode(parts[1]),new TextEncoder().encode(parts[0])))fail('Invalid media permission.',403);descriptor=JSON.parse(new TextDecoder().decode(decode(parts[0])));}catch{fail('Invalid media permission.',403);}if(!Number.isFinite(descriptor.expiresAt)||descriptor.expiresAt<Date.now())fail('Playback permission expired. Reload this result.',410);let key,mime;if(descriptor.shareId){if(!/^[a-f0-9]{32}$/.test(descriptor.shareId))fail('Invalid media permission.',403);const object=await env.RECORDINGS.get('shares/'+descriptor.shareId+'.json');if(!object)fail('Share link revoked or unavailable.',404);const snapshot=await object.json();key=snapshot.mediaKey;mime=snapshot.mime;}else{if(!/^[a-f0-9]{64}$/.test(descriptor.owner||'')||!/^[a-f0-9]{32}$/.test(descriptor.recordId||''))fail('Invalid media permission.',403);const object=await env.RECORDINGS.get(`owners/${descriptor.owner}/${descriptor.recordId}.json`);if(!object)fail('Recording unavailable.',404);const record=await object.json();if(record.deletedAt)fail('Recording is in trash.',410);key=`media/${descriptor.owner}/${descriptor.recordId}`;mime=record.mime;}if(!key||!mime)fail('Recording not included.',404);return mediaResponse(env.RECORDINGS,key,mime,request,{'cache-control':'no-store','referrer-policy':'no-referrer','x-content-type-options':'nosniff'});}
export async function cleanupUploads(env){let cursor;do{const page=await env.RECORDINGS.list({prefix:'uploads/grants/',limit:1000,...(cursor?{cursor}:{})});cursor=page.truncated?page.cursor:null;for(const entry of page.objects){const object=await env.RECORDINGS.get(entry.key);if(!object)continue;const grant=await object.json();if(grant.expiresAt>Date.now())continue;if(grant.status==='complete'){await env.RECORDINGS.delete(tempKey(grant));continue;}if(grant.status==='receiving'&&grant.expiresAt>Date.now()-1200000)continue;if(grant.status==='expired')continue;const committed=await env.RECORDINGS.get(dataKey(grant));const completed=committed?await committed.json():null;if(completed?.uploadId===grant.id&&completed.mime){grant.status='complete';await putGrant(env,grant,object).catch(()=>{});await env.RECORDINGS.delete(tempKey(grant));continue;}grant.status='expired';try{await putGrant(env,grant,object);}catch{continue;}await env.RECORDINGS.delete(tempKey(grant));const current=await env.RECORDINGS.get(dataKey(grant));const record=current?await current.json():null;if(record?.uploadId===grant.id&&record.mime)continue;await capacity(env,-grant.size);if(record&&!record.mime&&record.pendingUpload===grant.id&&record.revision===grant.placeholderRevision&&!record.transcript&&!record.result){record.purging=true;const claim=await env.RECORDINGS.put(dataKey(grant),JSON.stringify(record),{onlyIf:{etagMatches:current.etag}});if(claim!==null){await env.RECORDINGS.delete(dataKey(grant));await env.RECORDINGS.delete(mediaKey(grant));await capacity(env,0,-1);}}else if(!record)await env.RECORDINGS.delete(mediaKey(grant));}}while(cursor);}
