import { analysisSchema, analysisPrompt, validateLocalAnalysis } from '../local-analysis.js';
import { normalizeResult } from '../decision-policy.js';
import { assets } from './assets.generated.js';
import { locked, limit, mediaResponse, listAll, reserveQuota, warningMessages } from './storage-controls.js';
const MAX=25*1024*1024;
const etagSymbol=Symbol('storage-etag');
const mimeAllowed=new Set(['video/webm','video/mp4','audio/webm','audio/mp4','audio/mpeg','audio/wav','audio/x-wav','audio/ogg']);
const headers={'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; media-src 'self' blob:; img-src 'self' data: blob:; font-src 'self'; object-src 'none'; frame-ancestors 'none'"};
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...headers,'content-type':'application/json; charset=utf-8',...extra}});
const fail=(message,status=400,details={})=>{const e=new Error(message);e.status=status;e.details=details;throw e};
const id=()=>crypto.randomUUID().replaceAll('-','');
const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(byte=>byte.toString(16).padStart(2,'0')).join('');
async function owner(request){const token=/ps_owner=([a-f0-9]{32})/.exec(request.headers.get('cookie')||'')?.[1];if(!token)fail('Open the studio before saving a recording.',401);return hash(token)}
async function limited(request,max=MAX){const length=Number(request.headers.get('content-length'));if(length>max)fail(`Use an upload under ${Math.floor(max/1024/1024)} MB.`,413);const reader=request.body?.getReader();if(!reader)return new Uint8Array();const parts=[];let total=0;while(true){const {value,done}=await reader.read();if(done)break;total+=value.length;if(total>max){await reader.cancel();fail('Upload is too large.',413)}parts.push(value)}const bytes=new Uint8Array(total);let cursor=0;for(const part of parts){bytes.set(part,cursor);cursor+=part.length}return bytes}
const parse=async (request,max=350000)=>{try{return JSON.parse(new TextDecoder().decode(await limited(request,max)))}catch(error){if(error.status)throw error;fail('Invalid request data.')}};
const storage=env=>{if(!env.RECORDINGS)fail('Recording storage is not available. Your browser copy is preserved.',503);return env.RECORDINGS};
const key=(ownerHash,recordId)=>`owners/${ownerHash}/${recordId}.json`;
async function record(request,env,recordId,includeDeleted=false){if(!/^[a-f0-9]{32}$/.test(recordId))fail('Recording not found.',404);const ownerHash=await owner(request),object=await storage(env).get(key(ownerHash,recordId));if(!object){if(await storage(env).get('deleted/'+ownerHash+'/'+recordId+'.json'))fail('This recording was permanently deleted.',410,{deletedPermanently:true});fail('Recording not found in this workspace.',404);}const data=await object.json();if(object.etag)data[etagSymbol]=object.etag;data.revision=data.revision||1;if(data.deletedAt&&!includeDeleted)fail('This recording is in the recovery bin.',410,{revision:data.revision});return {ownerHash,data}}
async function save(env,ownerHash,data){data.updatedAt=new Date().toISOString();const creating=!data.revision;data.revision=(data.revision||0)+1;const onlyIf=data[etagSymbol]?{etagMatches:data[etagSymbol]}:creating?{etagDoesNotMatch:'*'}:null;const saved=await storage(env).put(key(ownerHash,data.id),JSON.stringify(data),{httpMetadata:{contentType:'application/json'},...(onlyIf?{onlyIf}:{})});if(saved===null){const current=await storage(env).get(key(ownerHash,data.id));fail('This recording changed during saving. Reload the saved version before retrying.',409,{revision:current?(await current.json()).revision:null})}if(saved?.etag)data[etagSymbol]=saved.etag}
async function purgeCopies(env,ownerHash,recordId,data={}){const bucket=storage(env),indexKey='share-index/'+ownerHash+'/'+recordId+'.json',indexObject=await bucket.get(indexKey),index=indexObject?await indexObject.json():{};for(const shareId of new Set([...(index.ids||[]),data.shareId].filter(Boolean)))await bucket.delete('shares/'+shareId+'.json');await bucket.delete('media/'+ownerHash+'/'+recordId);await bucket.put('deleted/'+ownerHash+'/'+recordId+'.json',JSON.stringify({id:recordId,cacheKeys:data.cacheKey?[data.cacheKey]:[],deletedAt:new Date().toISOString()}));await bucket.delete(key(ownerHash,recordId));await bucket.delete(indexKey);}
function publicData(data){const {id,kind,filename,mime,size,createdAt,updatedAt,transcript,transcriptSource,reviewed,segments,result,method,processingError,shareId,revision,deletedAt,processingStage,jobs}=data;return {id,kind,filename,mime,size,createdAt,updatedAt,transcript,transcriptSource,reviewed,segments,result,method,processingError,shareId,revision:revision||1,deletedAt:deletedAt||null,processingStage:processingStage||'recording-saved',jobs:jobs||{}}}
const str=value=>String(value||'').slice(0,3000);
function validResult(raw,transcript){
 if(!raw||!Array.isArray(raw.steps)||raw.steps.length>200||!Array.isArray(raw.actions)||raw.actions.length>200)fail('The process draft is not valid.');
 const fields=['title','summary','owner','trigger','outcome','exception','expectedOutcome','exceptionPath','method','model','modelVersion','modelSha256','policyVersion'];
 const result=Object.fromEntries(fields.map(field=>[field,str(raw[field])]));
 result.steps=raw.steps.map(step=>({...step,title:str(step.title),instruction:str(step.instruction),evidence:str(step.evidence),reason:str(step.reason),tools:Array.isArray(step.tools)?step.tools.map(str).slice(0,12):[],uncertainties:Array.isArray(step.uncertainties)?step.uncertainties.map(str).slice(0,12):[],decisionReviewed:Boolean(step.decisionReviewed&&step.evidence&&transcript.includes(step.evidence))}));
 result.actions=raw.actions.map(action=>({text:str(action.text),evidence:str(action.evidence),proposedText:str(action.proposedText),reviewRequired:Boolean(action.reviewRequired),done:Boolean(action.done)}));
 result.validation=raw.validation&&typeof raw.validation==='object'?JSON.parse(JSON.stringify(raw.validation)):null;
 result.issues=Array.isArray(raw.issues)?raw.issues.map(str).slice(0,100):[];
 result.warnings=Array.isArray(raw.warnings)?raw.warnings.map(str).slice(0,100):[];
 if(raw.provenance&&typeof raw.provenance==='object')result.provenance=Object.fromEntries(['engine','model','modelVersion','policyVersion','generatedAt','sourceRevision','sourceHash'].filter(field=>raw.provenance[field]!=null).map(field=>[field,str(raw.provenance[field])]));
 return normalizeResult(result,'model');
}
function requireCreator(request,env){if(!env.OPENAI_API_KEY)fail('Hosted AI is not configured yet. You can save recordings, edit a basic draft, and explore the labelled demo.',503);if(!env.CREATOR_CODE)fail('AI creation is paused until an access code is configured.',503);if(request.headers.get('x-studio-code')!==env.CREATOR_CODE)fail('Enter the creator access code to use hosted AI.',401)}
async function provider(path,body,env){const response=await fetch('https://api.openai.com/v1/'+path,{method:'POST',headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,...(body instanceof FormData?{}:{'content-type':'application/json'})},body:body instanceof FormData?body:JSON.stringify(body),signal:AbortSignal.timeout(150000)});if(!response.ok){console.error('AI provider request failed',response.status);fail(response.status===429?'The AI service is busy. Retry shortly.':'The AI service could not complete this request. Your recording is saved.',502)}return response.json()}
function checkRevision(data,input){if(input.expectedRevision!=null&&(!Number.isInteger(input.expectedRevision)||input.expectedRevision!==data.revision))fail('This recording changed since you opened it. Reload the saved version before retrying.',409,{revision:data.revision})}
async function processing(request,env,recordId,operation,input,perform){
 const lockKey=`record:${await owner(request)}:${recordId}`,operationKey=String(input.operationKey||request.headers.get('x-operation-key')||id());
 if(!/^[a-zA-Z0-9_-]{8,128}$/.test(operationKey))fail('Use an operation key between 8 and 128 characters.');
 const sourceHash=await hash(operation==='analyze'?String(input.transcript||'').trim():operation);
 let snapshot,cached;
 await locked(lockKey,async()=>{const {data,ownerHash}=await record(request,env,recordId);data.jobs||={};const job=data.jobs[operation];
  if(job?.operationKey===operationKey&&job.status==='complete'){if(job.sourceHash!==sourceHash||job.resultRevision!==data.revision)fail('The completed operation belongs to an older source revision. Use a new operation key.',409,{revision:data.revision});cached=operation==='analyze'?{...data.result,revision:data.revision}:{transcript:data.transcript,source:data.transcriptSource,segments:data.segments,timestamped:false,revision:data.revision};return}
  checkRevision(data,input);if(Object.values(data.jobs).some(item=>item.status==='working'&&Date.parse(item.leaseUntil)>Date.now()))fail('This recording already has a processing request in progress.',409,{revision:data.revision,job});
  await reserveQuota(env,'aiRequests',1,limit(env,'MAX_DAILY_AI_REQUESTS',100),fail);
  data.jobs[operation]={operationKey,status:'working',sourceHash,startedAt:new Date().toISOString(),leaseUntil:new Date(Date.now()+180000).toISOString()};data.processingStage=operation==='analyze'?'analyzing':'transcribing';data.processingError=null;await save(env,ownerHash,data);snapshot={data,ownerHash,revision:data.revision};
 });
 if(cached)return json(cached);
 try{const output=await perform(snapshot.data);return await locked(lockKey,async()=>{const {data,ownerHash}=await record(request,env,recordId);if(data.revision!==snapshot.revision||data.jobs?.[operation]?.operationKey!==operationKey)fail('The source changed during processing. The newer saved source was preserved.',409,{revision:data.revision});if(operation==='analyze'){data.transcript=String(input.transcript).trim();data.result=output;data.method='hosted-model';if(snapshot.data.transcript!==data.transcript)data.reviewed=false;data.processingStage='needs-review'}else{data.transcript=output.transcript;data.transcriptSource=output.source;data.reviewed=false;data.result=null;data.method=null;data.segments=[];data.processingStage='transcribed'}data.jobs[operation]={...data.jobs[operation],status:'complete',completedAt:new Date().toISOString(),resultRevision:data.revision+1};data.processingError=null;await save(env,ownerHash,data);return json({...output,revision:data.revision})})}
 catch(error){await locked(lockKey,async()=>{const {data,ownerHash}=await record(request,env,recordId);if(data.jobs?.[operation]?.operationKey===operationKey&&data.jobs[operation].status==='working'){data.jobs[operation]={...data.jobs[operation],status:'failed',error:error.status?error.message:'Processing could not complete.',failedAt:new Date().toISOString()};data.processingStage='failed';data.processingError=data.jobs[operation].error;await save(env,ownerHash,data)}}).catch(()=>{});throw error}
}
export default {async fetch(request,env={}){const url=new URL(request.url),path=url.pathname;try{
 if(!['GET','HEAD'].includes(request.method)&&request.headers.get('origin')!==url.origin)return json({error:'This request must come from the studio.'},403);
 if(path==='/api/session'&&request.method==='GET'){const token=/ps_owner=([a-f0-9]{32})/.exec(request.headers.get('cookie')||'')?.[1]||id();return json({ready:true,ownership:'browser-cookie',recovery:'Keep workspace exports; clearing this cookie loses hosted ownership.'},200,{'set-cookie':`ps_owner=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000${url.protocol==='https:'?'; Secure':''}`})}
 if(path==='/api/workspace/deletions'&&request.method==='GET'){const ownerHash=await owner(request),objects=await listAll(storage(env),'deleted/'+ownerHash+'/');const records=await Promise.all(objects.map(async item=>(await storage(env).get(item.key)).json()));return json({ids:records.map(item=>item.id),records:records.map(item=>({id:item.id,cacheKeys:item.cacheKeys||[]}))})}
 if(path==='/api/workspace/recovery'&&request.method==='GET'){await owner(request);const token=/ps_owner=([a-f0-9]{32})/.exec(request.headers.get('cookie')||'')[1];return json({format:'process-studio-workspace-recovery',version:1,token,private:true,warning:'This private key gives access to your hosted workspace. Keep it offline and never share it.'},200,{'content-disposition':'attachment; filename=process-studio-private-workspace-key.json'})}
 if(path==='/api/workspace/recover'&&request.method==='POST'){const input=await parse(request);if(input.format!=='process-studio-workspace-recovery'||input.version!==1||!/^[a-f0-9]{32}$/.test(input.token||''))fail('Use a valid private workspace recovery key.');return json({recovered:true},200,{'set-cookie':`ps_owner=${input.token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=2592000${url.protocol==='https:'?'; Secure':''}`})}
 if(path==='/api/status')return json({ai:Boolean(env.OPENAI_API_KEY&&env.CREATOR_CODE),localSpeech:false,localOnly:false,hosted:true,storage:Boolean(env.RECORDINGS),speechEngine:'Hosted transcription',modelState:env.OPENAI_API_KEY?'ready':'not-configured',trust:'review-required',limits:{uploadBytes:Math.min(MAX,limit(env,'MAX_UPLOAD_BYTES',MAX)),workspaceRecordings:limit(env,'MAX_WORKSPACE_RECORDINGS',50),dailyUploadBytes:limit(env,'MAX_DAILY_UPLOAD_BYTES',250*1024*1024),dailyRecordings:limit(env,'MAX_DAILY_RECORDINGS',200),dailyAiRequests:limit(env,'MAX_DAILY_AI_REQUESTS',100)},resourceControlScope:'R2 conditional writes for counters and revisions; local adapters use process locks. Configure platform request-rate limits before public access.'});
 if(path==='/api/recordings'&&request.method==='GET'){const ownerHash=await owner(request),objects=await listAll(storage(env),`owners/${ownerHash}/`);const includeDeleted=url.searchParams.get('includeDeleted')==='true';const values=await Promise.all(objects.map(async item=>{try{const object=await storage(env).get(item.key);return object?await object.json():null}catch(error){if(!error.storageCorrupt)throw error;return {id:item.key.split('/').pop().replace('.json',''),kind:'notes',filename:'Damaged recording',createdAt:'1970-01-01T00:00:00.000Z',corrupted:true,recoverable:error.details?.recoverable}}}));const all=values.filter(value=>value&&(includeDeleted||!value.deletedAt)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||a.id.localeCompare(b.id));const after=url.searchParams.get('cursor');const found=after?all.findIndex(value=>value.id===after):-1;if(after&&found<0)fail('Library cursor expired. Refresh the library.');const count=Math.min(100,limit({pageSize:url.searchParams.get('limit')},'pageSize',100)),page=all.slice(found+1,found+1+count);return json({items:page.map(value=>({id:value.id,title:value.result?.title||value.filename||'Written walkthrough',createdAt:value.createdAt,updatedAt:value.updatedAt,kind:value.kind,hasResult:Boolean(value.result),revision:value.revision||1,deletedAt:value.deletedAt||null,processingStage:value.processingStage||'recording-saved',corrupted:Boolean(value.corrupted),recoverable:Boolean(value.recoverable)})),cursor:all.length>found+1+count?page.at(-1).id:null,total:all.length})}
 if(path==='/api/recordings'&&request.method==='POST'){const ownerHash=await owner(request),bucket=storage(env),clientKey=request.headers.get('x-recording-key');if(clientKey&&!/^[a-zA-Z0-9_-]{8,128}$/.test(clientKey))fail('Use a recording key between 8 and 128 characters.');return await locked(`create:${ownerHash}`,async()=>{const retryId=clientKey?(await hash(ownerHash+':'+clientKey)).slice(0,32):null;if(retryId){if(await bucket.get('deleted/'+ownerHash+'/'+retryId+'.json'))fail('This recording was permanently deleted. Start a new walkthrough to save a separate copy.',410);const stored=await bucket.get(key(ownerHash,retryId));if(stored)return json(publicData(await stored.json()),200)}const existing=await listAll(bucket,`owners/${ownerHash}/`);if(existing.length>=limit(env,'MAX_WORKSPACE_RECORDINGS',50))fail('This workspace has reached its recording limit. Permanently remove recordings from the recovery bin to free space.',429);const mime=(request.headers.get('content-type')||'').split(';')[0],recordId=retryId||id();let bytes=null,kind='notes',filename='Written walkthrough';if(mime==='application/json'){const data=await parse(request);filename=String(data.filename||filename).slice(0,120);kind=data.kind==='sample'?'sample':'notes'}else{if(!mimeAllowed.has(mime))fail('Use WebM, MP4, MP3, WAV or OGG.',415);bytes=await limited(request,Math.min(MAX,limit(env,'MAX_UPLOAD_BYTES',MAX)));if(!bytes.length)fail('The recording is empty.');kind=['screen','audio','import'].includes(request.headers.get('x-recording-kind'))?request.headers.get('x-recording-kind'):'import';filename=decodeURIComponent(request.headers.get('x-recording-name')||'walkthrough.webm').slice(0,120)}await reserveQuota(env,'recordings',1,limit(env,'MAX_DAILY_RECORDINGS',200),fail);if(bytes)await reserveQuota(env,'uploadBytes',bytes.length,limit(env,'MAX_DAILY_UPLOAD_BYTES',250*1024*1024),fail);const data={id:recordId,kind,filename,mime:bytes?mime:null,size:bytes?.length||0,createdAt:new Date().toISOString(),transcript:'',transcriptSource:'Pending',reviewed:false,segments:[],result:null,method:null,shareId:null,revision:0,processingStage:'recording-saved',jobs:{},cacheKey:clientKey||null};try{if(bytes)await bucket.put(`media/${ownerHash}/${recordId}`,bytes,{httpMetadata:{contentType:mime}});await save(env,ownerHash,data)}catch(error){const existingRecord=await bucket.get(key(ownerHash,recordId)).catch(()=>null);if(!existingRecord)await bucket.delete(`media/${ownerHash}/${recordId}`).catch(()=>{});throw error}return json(publicData(data),201)})}
 const route=/^\/api\/recordings\/([a-f0-9]{32})(?:\/(video|transcribe|share|restore|purge|recover|damaged))?$/.exec(path);
 if(route){const operation=route[2],recordId=route[1];
  if(operation==='damaged'&&request.method==='GET'){const ownerHash=await owner(request),object=await storage(env).get(key(ownerHash,recordId));if(!object)fail('Recording not found.',404);return new Response(object.body,{headers:{...headers,'content-type':'application/octet-stream','content-disposition':'attachment; filename=damaged-recording.json'}})}
  if(operation==='damaged'&&request.method==='DELETE'){const ownerHash=await owner(request),bucket=storage(env);return await locked(`record:${ownerHash}:${recordId}`,async()=>{const object=await bucket.get(key(ownerHash,recordId));if(!object)fail('Recording not found.',404);let damaged=false;try{await object.json()}catch(error){if(!error.storageCorrupt)throw error;damaged=true}if(!damaged)fail('This recording is healthy. Move it to trash first.',409);const previous=await bucket.get(key(ownerHash,recordId)+'.previous');let data={};if(previous){try{data=await previous.json()}catch{}}await purgeCopies(env,ownerHash,recordId,data);return json({purged:true})})}
  if(operation==='recover'&&request.method==='POST'){const ownerHash=await owner(request),bucket=storage(env);return await locked(`record:${ownerHash}:${recordId}`,async()=>{if(await bucket.get('deleted/'+ownerHash+'/'+recordId+'.json'))fail('This recording was permanently deleted.',410);if(!bucket.recover)fail('Saved-version recovery is available in the local edition.',409);await bucket.recover(key(ownerHash,recordId));const {data}=await record(request,env,recordId,true);return json(publicData(data))})}
  if(operation==='transcribe'&&request.method==='POST'){requireCreator(request,env);const input=(request.headers.get('content-type')||'').startsWith('application/json')?await parse(request):{};return await processing(request,env,recordId,'transcribe',input,async data=>{if(!data.mime)fail('This walkthrough has no recording.');const object=await storage(env).get(`media/${await owner(request)}/${data.id}`);if(!object)fail('Recording unavailable.',404);const form=new FormData();form.append('model',env.TRANSCRIPTION_MODEL||'gpt-4o-mini-transcribe');form.append('file',new Blob([object.arrayBuffer?await object.arrayBuffer():await new Response(object.body).arrayBuffer()],{type:data.mime}),data.filename);form.append('response_format','json');const output=await provider('audio/transcriptions',form,env);if(!output.text?.trim())fail('No speech was found. Paste or correct the transcript instead.',422);return {transcript:output.text.trim(),source:'Hosted transcription',segments:[],timestamped:false}})}
  if(operation==='video'&&['GET','HEAD'].includes(request.method)){const {ownerHash,data}=await record(request,env,recordId,url.searchParams.get('includeDeleted')==='true');return mediaResponse(storage(env),`media/${ownerHash}/${data.id}`,data.mime,request,headers)}
  if(!operation&&request.method==='GET'){const {data}=await record(request,env,recordId,url.searchParams.get('includeDeleted')==='true');return json({...publicData(data),cacheKey:data.cacheKey||null,videoUrl:data.mime?`/api/recordings/${data.id}/video${data.deletedAt?'?includeDeleted=true':''}`:null})}
  return await locked(`record:${await owner(request)}:${recordId}`,async()=>{const {ownerHash,data}=await record(request,env,recordId,operation==='restore'||operation==='purge'||request.method==='DELETE');
   if(operation==='restore'&&request.method==='POST'){if(data.purging)fail('This recording is being permanently removed.',409);data.deletedAt=null;await save(env,ownerHash,data);return json(publicData(data))}
   if(operation==='purge'&&request.method==='DELETE'){if(!data.deletedAt)fail('Move this recording to the recovery bin before permanently removing it.');data.purging=true;await save(env,ownerHash,data);await purgeCopies(env,ownerHash,data.id,data);return json({purged:true})}
   if(!operation&&request.method==='DELETE'){if(data.shareId)await storage(env).delete(`shares/${data.shareId}.json`);data.shareId=null;data.deletedAt=new Date().toISOString();await save(env,ownerHash,data);return json(publicData(data))}
   if(operation==='share'&&request.method==='POST'){const input=await parse(request);checkRevision(data,input);if(input.consent!==true)fail('Confirm that this snapshot can be viewed by anyone with its link.');if(!data.result||data.method==='stale')fail('Generate or update a current process before sharing.');if(data.mime&&!data.reviewed)fail('Check the transcript against the recording before sharing.');if(!data.result.steps.length||data.result.steps.some(step=>!step.decisionReviewed))fail('Review every process decision before sharing.');const warnings=warningMessages(data.result);if(warnings.length&&!input.warningsAcknowledged)fail('Acknowledge the source and instruction warnings before sharing.',400,{warnings});const shareId=id();const snapshot={...publicData(data),id:undefined,shareId:undefined,jobs:undefined,sharedAt:new Date().toISOString(),warningsAcknowledged:Boolean(input.warningsAcknowledged),includeVideo:Boolean(input.includeVideo&&data.mime),mediaKey:input.includeVideo&&data.mime?`media/${ownerHash}/${data.id}`:null};const previousShare=data.shareId;await storage(env).put(`shares/${shareId}.json`,JSON.stringify(snapshot),{httpMetadata:{contentType:'application/json'}});data.shareId=shareId;try{const indexKey='share-index/'+ownerHash+'/'+data.id+'.json',previousIndex=await storage(env).get(indexKey),index=previousIndex?await previousIndex.json():{};await storage(env).put(indexKey,JSON.stringify({ids:[...new Set([...(index.ids||[]),shareId])]}));await save(env,ownerHash,data)}catch(error){await storage(env).delete(`shares/${shareId}.json`).catch(()=>{});throw error}if(previousShare)await storage(env).delete(`shares/${previousShare}.json`);return json({shareId,url:`${url.origin}/s/${shareId}`,revision:data.revision},201)}
   if(operation==='share'&&request.method==='DELETE'){if(data.shareId)await storage(env).delete(`shares/${data.shareId}.json`);data.shareId=null;await save(env,ownerHash,data);return json({revoked:true,revision:data.revision})}
   if(!operation&&request.method==='PUT'){const input=await parse(request,4*1024*1024);checkRevision(data,input);const transcript=String(input.transcript??data.transcript),changed=transcript!==data.transcript;if(transcript.length>200000)fail('The source exceeds the 200,000-character storage limit. Your previous saved source is unchanged. Export or split the source before saving.',413);if(Array.isArray(input.segments)&&input.segments.length>10000)fail('The source exceeds the 10,000 timed-phrase storage limit. Your previous saved source is unchanged.',413);data.transcript=transcript;data.reviewed=input.reviewed==null?(changed?false:data.reviewed):Boolean(input.reviewed);if(changed&&!input.result&&data.result)data.method='stale';data.transcriptSource=String(input.transcriptSource||data.transcriptSource).slice(0,120);if(Array.isArray(input.segments))data.segments=input.segments;if(input.result)data.result=validResult(input.result,transcript);data.method=String(changed&&!input.result&&data.result?'stale':input.method||data.method||'manual').slice(0,50);if(input.result)data.processingStage='needs-review';else if(changed)data.processingStage='transcribed';await save(env,ownerHash,data);return json(publicData(data))}
   fail('Not found.',404);
  });
 }
 if(path==='/api/analyze'&&request.method==='POST'){requireCreator(request,env);const input=await parse(request),transcript=String(input.transcript||'').trim();if(transcript.length<20||transcript.length>12000)fail('Use a walkthrough between 20 and 12,000 characters.');return await processing(request,env,input.id,'analyze',input,async()=>{const schema=structuredClone(analysisSchema);const output=await provider('chat/completions',{model:env.ANALYSIS_MODEL||'gpt-4.1-mini',temperature:0,max_completion_tokens:6000,response_format:{type:'json_schema',json_schema:{name:'process',strict:true,schema}},messages:[{role:'system',content:analysisPrompt},{role:'user',content:transcript}]},env);const choice=output.choices?.[0];if(choice?.finish_reason==='length'||choice?.message?.refusal)fail('The model could not produce a complete process. Shorten the walkthrough or retry.',422);let raw,result;try{raw=JSON.parse(choice?.message?.content||'{}');result=validateLocalAnalysis(raw,transcript)}catch(error){fail(error.message||'The AI response could not be validated. Retry this stage.',422)}Object.assign(result,{method:'hosted-model',model:env.ANALYSIS_MODEL||'gpt-4.1-mini',policyVersion:result.policyVersion||'2026-10-03-v2'});return result})}
 const shared=/^\/api\/shared\/([a-f0-9]{32})(?:\/(video))?$/.exec(path);
 if(shared&&['GET','HEAD'].includes(request.method)){const object=await storage(env).get(`shares/${shared[1]}.json`);if(!object)fail('This shared result is unavailable or its link was revoked.',404);const snapshot=await object.json();if(shared[2]){if(!snapshot.mediaKey)fail('The recording was not included.',404);return mediaResponse(storage(env),snapshot.mediaKey,snapshot.mime,request,headers)}const {mediaKey,...safe}=snapshot;return json({...safe,videoUrl:mediaKey?`/api/shared/${shared[1]}/video`:null})}
 if(path.startsWith('/api/'))return json({error:'Not found.'},404);
 const assetPath=/^\/(r|s)\/[a-f0-9]{32}$/.test(path)?'/result.html':path==='/'?'/index.html':path;
 const asset=assets[assetPath];if(!asset)return json({error:'Page not found.'},404);const body=asset.binary?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body;return new Response(request.method==='HEAD'?null:body,{headers:{...headers,'content-type':asset.type}});
 }catch(error){if(!error.status)console.error('Studio request failed',path,error.message);return json({error:error.status?error.message:'The request could not complete. Your saved work is preserved.',...error.details},error.status||500)}}};
